Netgen\LiveVotingBundle\Entity\Presentation:

    type: entity
    table: presentation
    id:
        id:
            type: integer
            generator: {strategy: AUTO}
    fields:
        presenterName:
            type: string
            length: 64
        presenterSurname:
            type: string
            length: 64
        presentationName:
            type: string
            length: 256
        votingEnabled:
            type: boolean
            default: false
#        sex: #yes please
#            type: string
#            lenght: 10 # m,f, team,...?
#            default: m
        country:
            type: string
            length: 128
        image:
            type: string
            length: 255
            nullable: true
        begin:
            type: datetime
        end:
            type: datetime

    oneToMany:
        votes:
            targetEntity: Netgen\LiveVotingBundle\Entity\Vote
            mappedBy: presentation

    manyToOne:
        event:
            targetEntity: Netgen\LiveVotingBundle\Entity\Event
            inversedBy: presentations
            joinColumn:
                name: event_id
                referencedColumnId: id
        user:
            targetEntity: Netgen\LiveVotingBundle\Entity\User
            inversedBy: presentations
            joinColumn:
                name: user_id
                referencedColumnId: id