parameters:
    live_voting.result.class: Netgen\LiveVotingBundle\Features\Result\Result
    live_voting.handleRequest.class: Netgen\LiveVotingBundle\Features\Request\ValidateRequest
    live_voting_question.result.class: Netgen\LiveVotingBundle\Features\Result\Result
    live_voting_question.handleRequest.class: Netgen\LiveVotingBundle\Features\Request\ValidateRequest
services:
#    live_voting.example:
#        class: %live_voting.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    live_voting.result:
          class: %live_voting.result.class%
          arguments: [@doctrine.orm.entity_manager, event_id]
    live_voting.handleRequest:
          class: %live_voting.handleRequest.class%
    live_voting_question.result:
          class: %live_voting_question.result.class%
          arguments: [@doctrine.orm.entity_manager, event_id]
    live_voting_question.handleRequest:
          class: %live_voting_question.handleRequest.class%    