admin_event:
    path:     /
    defaults: { _controller: "LiveVotingBundle:EventAdmin:index" }

admin_event_new:
    path:     /new
    defaults: { _controller: "LiveVotingBundle:EventAdmin:new" }

admin_event_create:
    path:     /create
    defaults: { _controller: "LiveVotingBundle:EventAdmin:create" }
    requirements: { _method: post }

admin_event_edit:
    path:     /{id}/edit
    defaults: { _controller: "LiveVotingBundle:EventAdmin:edit" }

admin_event_update:
    path:     /{id}/update
    defaults: { _controller: "LiveVotingBundle:EventAdmin:update" }
    requirements: { _method: post|put }


admin_event_enabledisable:
    path:     /enableDisable
    defaults: { _controller: "LiveVotingBundle:EventAdmin:enableDisable" }
    requirements: { _method: post }

admin_event_delete:
    path:     /{id}/delete
    defaults: { _controller: "LiveVotingBundle:EventAdmin:delete" }